# ---------------------------------------------------------------------------
# AnnoTemplate_StdAnno_CreateFC_subscript.py
# Created on: Tue Ocotober 31 2005 06:30:02 AM
#   (generated by ArcGIS/ModelBuilder)
# Created by: Laura Gordon, Polk County
# Usage: AnnoTemplate_StdAnno_CreateFC_subscript <Line_Coverage> <Point_Coverage> 
# ---------------------------------------------------------------------------
# Import system modules
import sys, string, os, win32com.client

# Create the Geoprocessor object
gp = win32com.client.Dispatch("esriGeoprocessing.GpDispatch.1")

# Feature Layer Argument
strInput = sys.argv[1]

# Add single quote around the path name to make the function work.
strInput = "'" + strInput + "'"

# Convert to geodatabase
StdAnno_10_FINAL_location = "P:\\ModelingWorkshop_10-13-05\\PolkCounty\\ORMAP-SchemaN-09-21-05.mdb\\JUNKY4"
gp.ImportCoverageAnnotation_conversion("'StdAnno.igds 100 scale'", StdAnno_10_FINAL_location, "1200", "CLASSES_FROM_LEVELS", "NO_MATCH", "NO_SYMBOL_REQUIRED", "STANDARD", "", "AUTO_CREATE", "AUTO_UPDATE")


#gp.ImportCoverageAnnotation_conversion(strInput, "P:\\ModelingWorkshop_10-13-05\\PolkCounty\\ORMAP-SchemaN-09-21-05.mdb\\JUNKY2", "1200", "CLASSES_FROM_LEVELS", "NO_MATCH", "NO_SYMBOL_REQUIRED", "STANDARD", "", "AUTO_CREATE", "AUTO_UPDATE")                          

###gp.ImportCoverageAnnotation_conversion("'c:\\temp\\taxmap\\annotation.igds'","c:\\temp\ORMAP.mdb\\JUNKY","500")
gp.addmessage("Created a new feature class")
