# ---------------------------------------------------------------------------
# AnnoTemplate_UpdateDegreeSymbol.py
# Updated on: Tue Dec13 2005
#   (generated by ArcGIS/ModelBuilder)
# ---------------------------------------------------------------------------

# Import system modules
import sys, string, os, win32com.client

Anno0100scale = sys.argv[1]
#CountyCode = sys.argv[2]

# Create the Geoprocessor object
gp = win32com.client.Dispatch("esriGeoprocessing.GpDispatch.1")
gp.addmessage("CAN IT GET HERE?")

# Create an Update cursor for MapIndex in order to calculate MapScale.
#cur = gp.UpdateCursor(Anno0100Scale, "[TextString] <> ''")
gp.Workspace = "P:/ModelingWorkshop_10-13-05/PolkCounty/ORMAP-SchemaN-09-21-05.mdb"
cur = gp.UpdateCursor ("CartographicLines")
row = cur.Next()
while row:
    gp.addmessage("Inside while")
    
    #text = "cc^^^cc"
    #stringreplace = string.replace(text, "^", "°"))
    #gp.addmessage(stringreplace)
   
    
    #row.TextString = string.replace(row.TextString, "^", "%")
    #row.[TextString] = string.replace(row.[TextString], "^", "%")
    cur.UpdateRow(row)
    row = cur.Next()

gp.addmessage("After while")