# ---------------------------------------------------------------------------
# CartoLines_MakeLines_subscript.py
# Created on: Monday October 24, 2005
#   (generated by ArcGIS/ModelBuilder)
# Usage: CartoLines_MakeLines_subscript <Line_Coverage> <Point_Coverage> 
# ---------------------------------------------------------------------------

# Import system modules
import sys, string, os, arcgisscripting

# Create the Geoprocessor object
gp = arcgisscripting.create()
gp.addmessage("1")

# Load required toolboxes...
gp.AddToolbox("C:/Program Files/ArcGIS/Desktop10.0/ArcToolbox/Toolboxes/Data Management Tools.tbx")

# Script arguments...
CartoLine_Feature2Line = sys.argv[1]
CartoLine = sys.argv[2]
gp.addmessage("2")

# Process: Make Feature Layer...
gp.MakeFeatureLayer_management(CartoLine_Feature2Line, "CartoLine_MakeLayer", "", "", "FNODE# FNODE# HIDDEN;TNODE# TNODE# HIDDEN;LPOLY# LPOLY# HIDDEN;RPOLY# RPOLY# HIDDEN;LENGTH LENGTH HIDDEN;CARTOLIN# CARTOLIN# HIDDEN;CARTOLIN-ID CARTOLIN-ID HIDDEN;LINETYPE LineType VISIBLE;MAPSCALE MapScale VISIBLE;MAPNUMBER MapNumber VISIBLE;AUTODATE AutoDate VISIBLE;AUTOMETHOD AutoMethod VISIBLE;AUTOWHO AutoWho VISIBLE")
gp.addmessage("Executed MakeFeatureLayer")

# Process: Append...
gp.addmessage("3")
gp.Append_management("CartoLine_MakeLayer", CartoLine, "TEST", )
gp.addmessage("Executed Append")

