# ---------------------------------------------------------------------------
# ConAll_MapIndex_subscript.py
# Created on: Monday October 31, 2005
#   (generated by ArcGIS/ModelBuilder)
# Usage: ConAll_MapIndex_subscript <Line_Coverage> <Point_Coverage> 
# ---------------------------------------------------------------------------

# Import system modules
import sys, string, os, arcgisscripting

# Create the Geoprocessor object
gp = arcgisscripting.create()
gp.addmessage("1")

# Load required toolboxes...
gp.AddToolbox("C:/Program Files/ArcGIS/Desktop10.0/ArcToolbox/Toolboxes/Data Management Tools.tbx")
gp.addmessage("2")

# Script arguments...
MapIndexPoly_Feature2Poly = sys.argv[1]
MapIndexPoly = sys.argv[2]
gp.addmessage("3")

# Process: Make Feature Layer...
gp.MakeFeatureLayer_management(MapIndexPoly_Feature2Poly, "MapIndexPoly_MakeLayer", "", "", "AREA AREA HIDDEN;PERIMETER PERIMETER HIDDEN;MAPINDEX# MAPINDEX# HIDDEN;MAPINDEX-ID MAPINDEX-ID HIDDEN;MAPSCALE MapScale VISIBLE;MAPNUMBER MapNumber VISIBLE;PAGENUMBER PageNumber VISIBLE;ORMAPNUM ORMapNum VISIBLE;CITYNAME CityName VISIBLE;RELIACODE ReliaCode VISIBLE;AUTODATE AutoDate VISIBLE;AUTOMETHOD AutoMethod VISIBLE;AUTOWHO AutoWho VISIBLE")
#gp.MakeFeatureLayer_management(MapIndexPoly_Feature2Poly, "MapIndexPoly_MakeLayer", "", "", "AREA AREA HIDDEN;PERIMETER PERIMETER HIDDEN;MAPINDEX# MAPINDEX# HIDDEN;MAPINDEX-ID MAPINDEX-ID HIDDEN;MAPSCALE MapScale VISIBLE;MAPNUMBER MapNumber VISIBLE;ORMAPNUM ORMapNum VISIBLE;PAGENUMBER PageNumber VISIBLE;RELIACODE ReliaCode VISIBLE;AUTODATE AutoDate VISIBLE;AUTOMETHOD AutoMethod VISIBLE;AUTOWHO AutoWho VISIBLE")
gp.addmessage("Executed MakeFeatureLayer")
gp.addmessage("4")

# Process: Append...
gp.Append_management("MapIndexPoly_MakeLayer", MapIndexPoly, "TEST", )
gp.addmessage("Executed Append")

# Process: Calculate the MapScale value to be MapScale * 12
gp.CalculateField_management(MapIndexPoly, "MapScale", "[MapScale] * 12")
gp.addmessage("CALCULATED MAPSCALE!!!")
