# ---------------------------------------------------------------------------
# MapIndex_UpdateFields.py
# Updated on: Tue Dec21 2004
#   (generated by ArcGIS/ModelBuilder)
# ---------------------------------------------------------------------------

# Import system modules
import sys, string, os, arcgisscripting

MapIndex = sys.argv[1]
CountyCode = sys.argv[2]

# Create the Geoprocessor object
gp = arcgisscripting.create()
#gp = win32com.client.Dispatch("esriGeoprocessing.GpDispatch.1")
gp.addmessage("CAN IT GET HERE?")
#Set the workspace
#gp.workspace = "D:\\Temp\\ModelingWorkshop_09-15-04\\OR-Schema-Data.mdb\\Taxlots_FD"

# Process: Calculate the County field to equal Polk County (code = 27)
gp.CalculateField_management(MapIndex, "County", CountyCode)

# Create an Update cursor for MapIndex in order to calculate MapScale.
cur = gp.UpdateCursor(MapIndex, "[MapNumber] <> ''")

# Get the first row from the MapIndex feature class.
row = cur.Next()
   
# Loop through each row and update MapScale based on MapNumber value.
#gp.addmessage("Before While")
while row:
    scale = row.MapNumber
    if len(scale) > 0:
        pos1 = scale[-1]
        pos2 = scale[-2]
        if pos1 == "A" or pos1 == "B" or pos1 == "C" or pos1 == "D": 
            if pos2 == "A" or pos2 == "B" or pos2 == "C" or pos2 == "D":
                row.MapScale = 1200
                cur.UpdateRow(row)
            else:
                row.MapScale = 2400
                cur.UpdateRow(row)
        elif len(scale) > 4:
            row.MapScale = 4800
            cur.UpdateRow(row) 
        else:
            row.MapScale = 24000
            cur.UpdateRow(row)    
    row = cur.Next()

del cur
