# ---------------------------------------------------------------------------
# PLSSLines_MakeLines_subscript.py
# Created on: Monday October 24, 2005
#   (generated by ArcGIS/ModelBuilder)
# Usage: PLSSLines_MakeLines_subscript <Line_Coverage> <Point_Coverage> 
# ---------------------------------------------------------------------------

# Import system modules
import sys, string, os, arcgisscripting

# Create the Geoprocessor object
gp = arcgisscripting.create()
gp.addmessage("1")

# Load required toolboxes...
gp.AddToolbox("C:/Program Files/ArcGIS/Desktop10.0/ArcToolbox/Toolboxes/Data Management Tools.tbx")

# Script arguments...
PLSSLine_Feature2Line = sys.argv[1]
PLSSLine = sys.argv[2]
gp.addmessage("2")

# Process: Make Feature Layer...
gp.MakeFeatureLayer_management(PLSSLine_Feature2Line, "PLSSLine_MakeLayer", "", "", "FNODE# FNODE# HIDDEN;TNODE# TNODE# HIDDEN;LPOLY# LPOLY# HIDDEN;RPOLY# RPOLY# HIDDEN;LENGTH LENGTH HIDDEN;PLSSLINE# PLSSLINE# HIDDEN;PLSSLINE-ID PLSSLINE-ID HIDDEN;PLSSLINE1# PLSSLINE1# HIDDEN;PLSSLINE1-ID PLSSLINE1-ID HIDDEN;DISTANCE Distance VISIBLE;RADIUS Radius VISIBLE;DELTA Delta VISIBLE;TANGENT Tangent VISIBLE;ARCLENGTH ArcLength VISIBLE;SIDE Side VISIBLE;RADIUS2 Radius2 VISIBLE;TANGENT2 Tangent2 VISIBLE;LINETYPE LineType VISIBLE;SOURCE Source VISIBLE;SOURCETYPE SourceType VISIBLE;DIRECTION Direction VISIBLE;MAPSCALE MapScale VISIBLE;MAPNUMBER MapNumber VISIBLE;RELIACODE ReliaCode VISIBLE;AUTODATE AutoDate VISIBLE;AUTOMETHOD AutoMethod VISIBLE;AUTOWHO AutoWho VISIBLE")
gp.addmessage("Executed MakeFeatureLayer")

# Process: Append...
gp.addmessage("3")
gp.Append_management("PLSSLine_MakeLayer", PLSSLine, "TEST", )
gp.addmessage("Executed Append")

