# ---------------------------------------------------------------------------
# RefLines_MakeLines_subscript.py
# Created on: Monday October 24, 2005
#   (generated by ArcGIS/ModelBuilder)
# Usage: RefLines_MakeLines_subscript <Line_Coverage> <Point_Coverage> 
# ---------------------------------------------------------------------------

# Import system modules
import sys, string, os, arcgisscripting

# Create the Geoprocessor object
gp = arcgisscripting.create()
gp.addmessage("1")

# Load required toolboxes...
gp.AddToolbox("C:/Program Files/ArcGIS/Desktop10.0/ArcToolbox/Toolboxes/Data Management Tools.tbx")

# Script arguments...
RefLine_Feature2Line = sys.argv[1]
RefLine = sys.argv[2]
gp.addmessage("2")

# Process: Make Feature Layer...
gp.MakeFeatureLayer_management(RefLine_Feature2Line, "RefLine_MakeLayer", "", "", "FNODE# FNODE# HIDDEN;TNODE# TNODE# HIDDEN;LPOLY# LPOLY# HIDDEN;RPOLY# RPOLY# HIDDEN;LENGTH LENGTH HIDDEN;REFLIN# REFLIN# HIDDEN;REFLIN-ID REFLIN-ID HIDDEN;IGDS-STYLE IGDS-STYLE HIDDEN;DIRECTION Direction VISIBLE;DISTANCE Distance VISIBLE;RADIUS Radius VISIBLE;DELTA Delta VISIBLE;TANGENT Tangent VISIBLE;ARCLENGTH ArcLength VISIBLE;SIDE Side VISIBLE;RADIUS2 Radius2 VISIBLE;TANGENT2 Tangent2 VISIBLE;DETAILSCALE DETAILSCALE HIDDEN;SVYNUM SVYNUM HIDDEN;TAXLOTKEY TAXLOTKEY HIDDEN;LINETYPE LineType VISIBLE;MAPSCALE MapScale VISIBLE;MAPNUMBER MapNumber VISIBLE;SOURCE Source VISIBLE;SOURCETYPE SourceType VISIBLE;RELIACODE ReliaCode VISIBLE;AUTODATE AutoDate VISIBLE;AUTOMETHOD AutoMethod VISIBLE;AUTOWHO AutoWho VISIBLE;LOSTATION LoStation VISIBLE;HISTATION HiStation VISIBLE")
gp.addmessage("Executed MakeFeatureLayer")

# Process: Append...
gp.addmessage("3")
gp.Append_management("RefLine_MakeLayer", RefLine, "TEST", )
gp.addmessage("Executed Append")

