# ---------------------------------------------------------------------------
# MapIndex_UpdateFields.py
# Created on: Tue Aug 31 2004 11:27:56 AM
#   (generated by ArcGIS/ModelBuilder)
# ---------------------------------------------------------------------------

# Import system modules
import sys, string, os, win32com.client

Taxlot = sys.argv[1]
CountyCode = sys.argv[2]

# Create the Geoprocessor object
gp = win32com.client.Dispatch("esriGeoprocessing.GpDispatch.1")

# Calculate the County field to equal Polk County (code = 27)
gp.CalculateField_management(Taxlot, "County", CountyCode)

# Calculate the MapAcres field to equal Shape_Area / 43560 and rounded to 3 decimal places
cur1 = gp.UpdateCursor(Taxlot)
row1 = cur1.Next()
while row1:
    Acres = row1.Shape_Area / 43560
    RoundedAcres = round(Acres, 3)
    row1.MapAcres = RoundedAcres
    cur1.UpdateRow(row1)
    row1 = cur1.Next()
del cur1

# Calculate Qtr and QtrQtr fields based on MapNumber value
cur2 = gp.UpdateCursor(Taxlot)
row2 = cur2.Next()
while row2:
    scale = row2.MapNumber
    if len(scale) > 0:
        pos1 = scale[-1]
        pos2 = scale[-2]
    if pos1 == "A" or pos1 == "B" or pos1 == "C" or pos1 == "D": 
        if pos2 == "A" or pos2 == "B" or pos2 == "C" or pos2 == "D":
            row2.Qtr = pos2
            row2.QtrQtr = pos1
            cur2.UpdateRow(row2)
        else:
            row2.qtr = pos1
            cur2.UpdateRow(row2)      
    row2 = cur2.Next()
del cur2

# Remove the leading spaces in the Taxlot values
cur3 = gp.UpdateCursor(Taxlot)
row3 = cur3.Next()
while row3:
    taxStr = row3.Taxlot
    trimStr = string.strip(taxStr)
    row3.Taxlot = trimStr
    cur3.UpdateRow(row3)
    row3 = cur3.Next()
del cur3
