# ---------------------------------------------------------------------------
# test.py
# Created on: Tue Jul 27 2004 02:30:02 PM
#   (generated by ArcGIS/ModelBuilder)
# Usage: test <Line_Coverage> <Point_Coverage> 
# ---------------------------------------------------------------------------

# Import system modules
import sys, string, os, win32com.client

# Create the Geoprocessor object
gp = win32com.client.Dispatch("esriGeoprocessing.GpDispatch.1")

# Script arguments...
Taxlot_SelArcs = sys.argv[1]
Taxlotlines = sys.argv[2]

# Process: Make Feature Layer...
gp.MakeFeatureLayer_management(Taxlot_SelArcs, "TaxlotLines_MakeLayer", "", "", "FNODE_ FNODE_ HIDDEN;TNODE_ TNODE_ HIDDEN;LPOLY_ LPOLY_ HIDDEN;RPOLY_ RPOLY_ HIDDEN;LENGTH LENGTH HIDDEN;TAXMAP_ TAXMAP_ HIDDEN;TAXMAP_ID TAXMAP_ID HIDDEN;ANGLE Direction VISIBLE;DISTANCE Distance VISIBLE;RADIUS Radius VISIBLE;DELTA Delta VISIBLE;TANGENT Tangent VISIBLE;ARCLENGTH ArcLength VISIBLE;SIDE Side VISIBLE;RADIUS2 Radius2 VISIBLE;TANGENT2 Tangent2 VISIBLE;TAXMAPSYM TAXMAPSYM HIDDEN;TAXMAPTYPE LineType VISIBLE;AUTO-METHOD AutoMethod VISIBLE;AUTO-REL AUTO-REL HIDDEN;AUTO-WHO AutoWho VISIBLE;AUTO-DATE AutoDate VISIBLE;GEOTRANSNO GEOTRANSNO HIDDEN;Shape_Length Shape_Length HIDDEN")
gp.addmessage("Executed MakeFeatureLayer")

# Process: Append...
gp.Append_management("TaxlotLInes_MakeLayer", Taxlotlines, "TEST", )
gp.addmessage("Executed Append")

