# ---------------------------------------------------------------------------
# WaterLines_MakeLines_subscript.py
# Created on: Monday October 24, 2005
#   (generated by ArcGIS/ModelBuilder)
# Usage: WaterLines_MakeLines_subscript <Line_Coverage> <Point_Coverage> 
# ---------------------------------------------------------------------------

# Import system modules
import sys, string, os, arcgisscripting

# Create the Geoprocessor object
gp = arcgisscripting.create()
gp.addmessage("1")

# Load required toolboxes...
gp.AddToolbox("C:/Program Files/ArcGIS/Desktop10.0/ArcToolbox/Toolboxes/Data Management Tools.tbx")

# Script arguments...
WaterLine_Feature2Line = sys.argv[1]
WaterLine = sys.argv[2]
gp.addmessage("2")

# Process: Make Feature Layer...
gp.MakeFeatureLayer_management(WaterLine_Feature2Line, "WaterLine_MakeLayer", "", "", "FNODE# FNODE# HIDDEN;TNODE# TNODE# HIDDEN;LPOLY# LPOLY# HIDDEN;RPOLY# RPOLY# HIDDEN;LENGTH LENGTH HIDDEN;WATERLIN# WATERLIN# HIDDEN;WATERLIN-ID WATERLIN-ID HIDDEN;IGDS-STYLE IGDS-STYLE HIDDEN;DETAILSCALE DETAILSCALE HIDDEN;SVYNUM SVYNUM HIDDEN;TAXLOTKEY TAXLOTKEY HIDDEN;WATERNAME WaterName VISIBLE;LINETYPE LineType VISIBLE;MAPSCALE MapScale VISIBLE;MAPNUMBER MapNumber VISIBLE;SOURCE Source VISIBLE;SOURCETYPE SourceType VISIBLE;RELIACODE ReliaCode VISIBLE;AUTODATE AutoDate VISIBLE;AUTOMETHOD AutoMethod VISIBLE;AUTOWHO AutoWho VISIBLE")
gp.addmessage("Executed MakeFeatureLayer")

# Process: Append...
gp.addmessage("3")
gp.Append_management("WaterLine_MakeLayer", WaterLine, "TEST", )
gp.addmessage("Executed Append")

