# -*- coding: utf-8 -*-
# ---------------------------------------------------------------------------
# 2.ConvertGenAnno.py
# Created on: 2017-05-24 15:31:40.00000
#   (generated by ArcGIS/ModelBuilder)
# Description: 
# ---------------------------------------------------------------------------

# Import arcpy module
import arcpy

# Functions ------------------------------------------------------------------------

#calcfield Functions - field calc sizes for annotation features

def CalcFields(Anno):
    # Process: Calculate Field
    arcpy.CalculateField_management(Anno, "FontName", "[STDFONT]", "VB", "")

    # Process: Calculate Field (2)
    arcpy.CalculateField_management(Anno, "FontSize", "[STDSIZE]", "VB", "")

    # Process: Calculate Field (3)
    arcpy.CalculateField_management(Anno, "Bold", "[STDBOLD]", "VB", "")

    # Process: Calculate Field (13)
    arcpy.CalculateField_management(Anno, "Italic", "[STDITALIC]", "VB", "")

    # Process: Calculate Field (17)
    arcpy.CalculateField_management(Anno, "TextString", "Replace( [TextString],\"^\",\"°\"  )", "VB", "")
    print ("Done with Calc- " + Anno)

    return;

# ImportAnno - Deletes anno feature and then converts the anno

def ImportAnno(AnnoCov,AnnoF):
    # Delete 
    arcpy.Delete_management(AnnoF)

    # Process: Import Coverage Annotation
    arcpy.ImportCoverageAnnotation_conversion(AnnoCov, AnnoF, "1200", "CLASSES_FROM_LEVELS", "NO_MATCH", "NO_SYMBOL_REQUIRED", "STANDARD", "", "AUTO_CREATE", "AUTO_UPDATE")

    print ("Done with import- " + AnnoF)
    
    return;

#--------------------------------------------------------------------------------------


# Local variables:

AnnoIGDS = "..\\taxmap\\annotation.igds" 
scales = ["0100","0200","0400","2000"] 


for scale in scales:
    AnnoScaleIGDS = "Anno" + scale + "IGDS"
    AnnoScale = "..\\townedgeo.gdb\\Anno" + scale + "Scale" 
    print AnnoScale
    
    #AnnoScale = "..\\townedgeo.gdb\\Anno0100Scale"  
    print AnnoScaleIGDS +  "---" + AnnoScale

    mapscale =  "mapscale = " + str(int(scale)) 
    print mapscale
                                         
    # Delete 
    arcpy.Delete_management(AnnoScale)

    # Process: Make Feature Layer
    arcpy.MakeFeatureLayer_management(AnnoIGDS, AnnoScaleIGDS, mapscale , "", "FID FID VISIBLE NONE;Shape Shape VISIBLE NONE;IGDS# IGDS# VISIBLE NONE;IGDS-ID IGDS-ID VISIBLE NONE;SYMBOL SYMBOL VISIBLE NONE;LEVEL LEVEL VISIBLE NONE;TEXT TEXT VISIBLE NONE;MAPSIZE MAPSIZE VISIBLE NONE;MAPSCALE MAPSCALE VISIBLE NONE;MAPNUMBER MAPNUMBER VISIBLE NONE;AUTOWHO AUTOWHO VISIBLE NONE;AUTOMETHOD AUTOMETHOD VISIBLE NONE;AUTODATE AUTODATE VISIBLE NONE;STDSIZE STDSIZE VISIBLE NONE;STDFONT STDFONT VISIBLE NONE;STDBOLD STDBOLD VISIBLE NONE;STDITALIC STDITALIC VISIBLE NONE;$ID $ID VISIBLE NONE;$SYMBOL $SYMBOL VISIBLE NONE;$LEVEL $LEVEL VISIBLE NONE;$SIZE $SIZE VISIBLE NONE;$TEXT $TEXT VISIBLE NONE;$OFFSETX $OFFSETX VISIBLE NONE;$OFFSETY $OFFSETY VISIBLE NONE;$JUSTIFY $JUSTIFY VISIBLE NONE;$FIT $FIT VISIBLE NONE;$ALIGN $ALIGN VISIBLE NONE")

    # Process: Import Coverage Annotation
    arcpy.ImportCoverageAnnotation_conversion(AnnoScaleIGDS, AnnoScale, "1200", "CLASSES_FROM_LEVELS", "NO_MATCH", "NO_SYMBOL_REQUIRED", "STANDARD", "", "AUTO_CREATE", "AUTO_UPDATE")
    print ("Done with import- " + scale) 

    # Calc fields (function)
    CalcFields(AnnoScale)

# Do Taxlot Anno

TaxlotAnnoCov = "..\\taxlotan\\annotation.igds"
TaxlotAnnoFeature = "..\\townedgeo.gdb\\TaxlotsFD\\TaxlotNumberAnno"
print TaxlotAnnoFeature

ImportAnno(TaxlotAnnoCov,TaxlotAnnoFeature)
CalcFields(TaxlotAnnoFeature)
print "Done with Taxlots Anno"

# Do Taxcode Anno

TaxCodeAnnoCov = "..\\taxcodan\\annotation.igds" 
TaxCodeAnnoFeature = "..\\townedgeo.gdb\\TaxlotsFD\\TaxCodeAnno"

ImportAnno(TaxCodeAnnoCov,TaxCodeAnnoFeature)
CalcFields(TaxCodeAnnoFeature)
print "Done with Taxcode Anno"


