# -*- coding: utf-8 -*-
# ---------------------------------------------------------------------------
# makepoly.py
# Created on: 2017-08-30 11:02:13.00000
#   (generated by ArcGIS/ModelBuilder)
# Description: 
# ---------------------------------------------------------------------------

# Set the necessary product code
# import arcinfo


# Import arcpy module
import arcpy


# Local variables:
MapIndexLines = "GeoDatabase\\MapIndexLines"
MapIndexPoints = "GeoDatabase\\MapIndexPoints"
MapIndex = "townedgeo.gdb\\TaxlotsFD\\MapIndex"
TaxlotLines = "GeoDatabase\\TaxlotLines"
TaxlotPoints = "GeoDatabase\\TaxlotPoints"
Taxlot = "townedgeo.gdb\\TaxlotsFD\\Taxlot"
TaxCodeLines = "GeoDatabase\\TaxCodeLines"
TaxCodePoints = "GeoDatabase\\TaxCodePoints"
TaxCode = "townedgeo.gdb\\TaxlotsFD\\TaxCode"

# Process: Feature To Polygon (3)
arcpy.FeatureToPolygon_management("GeoDatabase\\MapIndexLines", MapIndex, "", "ATTRIBUTES", MapIndexPoints)

# Process: Feature To Polygon
arcpy.FeatureToPolygon_management("GeoDatabase\\TaxlotLines", Taxlot, "", "ATTRIBUTES", TaxlotPoints)

# Process: Feature To Polygon (2)
arcpy.FeatureToPolygon_management("GeoDatabase\\TaxCodeLines", TaxCode, "", "ATTRIBUTES", TaxCodePoints)

