# -*- coding: utf-8 -*-
# ---------------------------------------------------------------------------
# 2.ConvertGenAnno.py
# Created on: 2017-05-24 15:31:40.00000
#   (generated by ArcGIS/ModelBuilder)
# Description: 
# ---------------------------------------------------------------------------

# Import arcpy module
import arcpy


# Local variables:
AnnoIGDS = "..\\taxmap\\annotation.igds" 

Anno100IGDS = "Anno100IGDS"
Anno200IGDS = "Anno200IGDS"
Anno400IGDS = "Anno400IGDS"
Anno2000IGDS = "Anno2000IGDS"

Anno0100Scale = "..\\townedgeo.gdb\\Anno0100Scale" 
Anno0200Scale = "..\\townedgeo.gdb\\Anno0200Scale" 
Anno0400Scale = "..\\townedgeo.gdb\\Anno0400Scale" 
Anno2000Scale = "..\\townedgeo.gdb\\Anno2000Scale" 

# Anno100

# Delete 
arcpy.Delete_management(Anno0100Scale)

# Process: Make Feature Layer
arcpy.MakeFeatureLayer_management(AnnoIGDS, Anno100IGDS, "\"MAPSCALE\" = 100", "", "FID FID VISIBLE NONE;Shape Shape VISIBLE NONE;IGDS# IGDS# VISIBLE NONE;IGDS-ID IGDS-ID VISIBLE NONE;SYMBOL SYMBOL VISIBLE NONE;LEVEL LEVEL VISIBLE NONE;TEXT TEXT VISIBLE NONE;MAPSIZE MAPSIZE VISIBLE NONE;MAPSCALE MAPSCALE VISIBLE NONE;MAPNUMBER MAPNUMBER VISIBLE NONE;AUTOWHO AUTOWHO VISIBLE NONE;AUTOMETHOD AUTOMETHOD VISIBLE NONE;AUTODATE AUTODATE VISIBLE NONE;STDSIZE STDSIZE VISIBLE NONE;STDFONT STDFONT VISIBLE NONE;STDBOLD STDBOLD VISIBLE NONE;STDITALIC STDITALIC VISIBLE NONE;$ID $ID VISIBLE NONE;$SYMBOL $SYMBOL VISIBLE NONE;$LEVEL $LEVEL VISIBLE NONE;$SIZE $SIZE VISIBLE NONE;$TEXT $TEXT VISIBLE NONE;$OFFSETX $OFFSETX VISIBLE NONE;$OFFSETY $OFFSETY VISIBLE NONE;$JUSTIFY $JUSTIFY VISIBLE NONE;$FIT $FIT VISIBLE NONE;$ALIGN $ALIGN VISIBLE NONE")

# Process: Import Coverage Annotation
arcpy.ImportCoverageAnnotation_conversion(Anno100IGDS, Anno0100Scale, "1200", "CLASSES_FROM_LEVELS", "NO_MATCH", "NO_SYMBOL_REQUIRED", "STANDARD", "", "AUTO_CREATE", "AUTO_UPDATE")
print ("Done with import") 

# Process: Calculate Field
arcpy.CalculateField_management(Anno0100Scale, "FontName", "[STDFONT]", "VB", "")

# Process: Calculate Field (2)
arcpy.CalculateField_management(Anno0100Scale, "FontSize", "[STDSIZE]", "VB", "")

# Process: Calculate Field (3)
arcpy.CalculateField_management(Anno0100Scale, "Bold", "[STDBOLD]", "VB", "")

# Process: Calculate Field (13)
arcpy.CalculateField_management(Anno0100Scale, "Italic", "[STDITALIC]", "VB", "")

# Process: Calculate Field (17)
arcpy.CalculateField_management(Anno0100Scale, "TextString", "Replace( [TextString],\"^\",\"°\"  )", "VB", "")
print ("Done with Calc") 

# Anno200

# Delete 
arcpy.Delete_management(Anno0200Scale)

# Process: Make Feature Layer
arcpy.MakeFeatureLayer_management(AnnoIGDS, Anno200IGDS, "\"MAPSCALE\" = 200", "", "FID FID VISIBLE NONE;Shape Shape VISIBLE NONE;IGDS# IGDS# VISIBLE NONE;IGDS-ID IGDS-ID VISIBLE NONE;SYMBOL SYMBOL VISIBLE NONE;LEVEL LEVEL VISIBLE NONE;TEXT TEXT VISIBLE NONE;MAPSIZE MAPSIZE VISIBLE NONE;MAPSCALE MAPSCALE VISIBLE NONE;MAPNUMBER MAPNUMBER VISIBLE NONE;AUTOWHO AUTOWHO VISIBLE NONE;AUTOMETHOD AUTOMETHOD VISIBLE NONE;AUTODATE AUTODATE VISIBLE NONE;STDSIZE STDSIZE VISIBLE NONE;STDFONT STDFONT VISIBLE NONE;STDBOLD STDBOLD VISIBLE NONE;STDITALIC STDITALIC VISIBLE NONE;$ID $ID VISIBLE NONE;$SYMBOL $SYMBOL VISIBLE NONE;$LEVEL $LEVEL VISIBLE NONE;$SIZE $SIZE VISIBLE NONE;$TEXT $TEXT VISIBLE NONE;$OFFSETX $OFFSETX VISIBLE NONE;$OFFSETY $OFFSETY VISIBLE NONE;$JUSTIFY $JUSTIFY VISIBLE NONE;$FIT $FIT VISIBLE NONE;$ALIGN $ALIGN VISIBLE NONE")

# Process: Import Coverage Annotation
arcpy.ImportCoverageAnnotation_conversion(Anno200IGDS, Anno0200Scale, "1200", "CLASSES_FROM_LEVELS", "NO_MATCH", "NO_SYMBOL_REQUIRED", "STANDARD", "", "AUTO_CREATE", "AUTO_UPDATE")
print ("Done with 200 import") 

# Process: Calculate Field
arcpy.CalculateField_management(Anno0200Scale, "FontName", "[STDFONT]", "VB", "")

# Process: Calculate Field (2)
arcpy.CalculateField_management(Anno0200Scale, "FontSize", "[STDSIZE]", "VB", "")

# Process: Calculate Field (3)
arcpy.CalculateField_management(Anno0200Scale, "Bold", "[STDBOLD]", "VB", "")

# Process: Calculate Field (13)
arcpy.CalculateField_management(Anno0200Scale, "Italic", "[STDITALIC]", "VB", "")

# Process: Calculate Field (17)
arcpy.CalculateField_management(Anno0200Scale, "TextString", "Replace( [TextString],\"^\",\"°\"  )", "VB", "")
print ("Done with 200 Calc")

# Anno400

# Delete 
arcpy.Delete_management(Anno0400Scale)

# Process: Make Feature Layer
arcpy.MakeFeatureLayer_management(AnnoIGDS, Anno400IGDS, "\"MAPSCALE\" = 400", "", "FID FID VISIBLE NONE;Shape Shape VISIBLE NONE;IGDS# IGDS# VISIBLE NONE;IGDS-ID IGDS-ID VISIBLE NONE;SYMBOL SYMBOL VISIBLE NONE;LEVEL LEVEL VISIBLE NONE;TEXT TEXT VISIBLE NONE;MAPSIZE MAPSIZE VISIBLE NONE;MAPSCALE MAPSCALE VISIBLE NONE;MAPNUMBER MAPNUMBER VISIBLE NONE;AUTOWHO AUTOWHO VISIBLE NONE;AUTOMETHOD AUTOMETHOD VISIBLE NONE;AUTODATE AUTODATE VISIBLE NONE;STDSIZE STDSIZE VISIBLE NONE;STDFONT STDFONT VISIBLE NONE;STDBOLD STDBOLD VISIBLE NONE;STDITALIC STDITALIC VISIBLE NONE;$ID $ID VISIBLE NONE;$SYMBOL $SYMBOL VISIBLE NONE;$LEVEL $LEVEL VISIBLE NONE;$SIZE $SIZE VISIBLE NONE;$TEXT $TEXT VISIBLE NONE;$OFFSETX $OFFSETX VISIBLE NONE;$OFFSETY $OFFSETY VISIBLE NONE;$JUSTIFY $JUSTIFY VISIBLE NONE;$FIT $FIT VISIBLE NONE;$ALIGN $ALIGN VISIBLE NONE")

# Process: Import Coverage Annotation
arcpy.ImportCoverageAnnotation_conversion(Anno400IGDS, Anno0400Scale, "1200", "CLASSES_FROM_LEVELS", "NO_MATCH", "NO_SYMBOL_REQUIRED", "STANDARD", "", "AUTO_CREATE", "AUTO_UPDATE")
print ("Done with 400 import") 

# Process: Calculate Field
arcpy.CalculateField_management(Anno0400Scale, "FontName", "[STDFONT]", "VB", "")

# Process: Calculate Field (2)
arcpy.CalculateField_management(Anno0400Scale, "FontSize", "[STDSIZE]", "VB", "")

# Process: Calculate Field (3)
arcpy.CalculateField_management(Anno0400Scale, "Bold", "[STDBOLD]", "VB", "")

# Process: Calculate Field (13)
arcpy.CalculateField_management(Anno0400Scale, "Italic", "[STDITALIC]", "VB", "")

# Process: Calculate Field (17)
arcpy.CalculateField_management(Anno0400Scale, "TextString", "Replace( [TextString],\"^\",\"°\"  )", "VB", "")
print ("Done with 400 Calc")


# Anno2000

# Delete 
arcpy.Delete_management(Anno2000Scale)

# Process: Make Feature Layer
arcpy.MakeFeatureLayer_management(AnnoIGDS, Anno2000IGDS, "\"MAPSCALE\" = 2000", "", "FID FID VISIBLE NONE;Shape Shape VISIBLE NONE;IGDS# IGDS# VISIBLE NONE;IGDS-ID IGDS-ID VISIBLE NONE;SYMBOL SYMBOL VISIBLE NONE;LEVEL LEVEL VISIBLE NONE;TEXT TEXT VISIBLE NONE;MAPSIZE MAPSIZE VISIBLE NONE;MAPSCALE MAPSCALE VISIBLE NONE;MAPNUMBER MAPNUMBER VISIBLE NONE;AUTOWHO AUTOWHO VISIBLE NONE;AUTOMETHOD AUTOMETHOD VISIBLE NONE;AUTODATE AUTODATE VISIBLE NONE;STDSIZE STDSIZE VISIBLE NONE;STDFONT STDFONT VISIBLE NONE;STDBOLD STDBOLD VISIBLE NONE;STDITALIC STDITALIC VISIBLE NONE;$ID $ID VISIBLE NONE;$SYMBOL $SYMBOL VISIBLE NONE;$LEVEL $LEVEL VISIBLE NONE;$SIZE $SIZE VISIBLE NONE;$TEXT $TEXT VISIBLE NONE;$OFFSETX $OFFSETX VISIBLE NONE;$OFFSETY $OFFSETY VISIBLE NONE;$JUSTIFY $JUSTIFY VISIBLE NONE;$FIT $FIT VISIBLE NONE;$ALIGN $ALIGN VISIBLE NONE")

# Process: Import Coverage Annotation
arcpy.ImportCoverageAnnotation_conversion(Anno2000IGDS, Anno2000Scale, "1200", "CLASSES_FROM_LEVELS", "NO_MATCH", "NO_SYMBOL_REQUIRED", "STANDARD", "", "AUTO_CREATE", "AUTO_UPDATE")
print ("Done with 2000 import") 

# Process: Calculate Field
arcpy.CalculateField_management(Anno2000Scale, "FontName", "[STDFONT]", "VB", "")

# Process: Calculate Field (2)
arcpy.CalculateField_management(Anno2000Scale, "FontSize", "[STDSIZE]", "VB", "")

# Process: Calculate Field (3)
arcpy.CalculateField_management(Anno2000Scale, "Bold", "[STDBOLD]", "VB", "")

# Process: Calculate Field (13)
arcpy.CalculateField_management(Anno2000Scale, "Italic", "[STDITALIC]", "VB", "")

# Process: Calculate Field (17)
arcpy.CalculateField_management(Anno2000Scale, "TextString", "Replace( [TextString],\"^\",\"°\"  )", "VB", "")
print ("Done with 2000 Calc")


